#source: /media/asbjoern/925bd160-9cb1-4f8c-b329-1a01a1555203/Hovedmappe, /media/asbjoern/925bd160-9cb1-4f8c-b329-1a01a1555203/Iphoto og foto/Fotos Library.photoslibrary
source: /home/asbjoern/Desktop/hovedmappe, /home/asbjoern/Desktop/iphoto
#destination: /media/asbjoern/925bd160-9cb1-4f8c-b329-1a01a1555203/main
destination: /home/asbjoern/Desktop/fotoorganiserOutput
